{ config, pkgs, ... }:
{
  wayland.windowManager.hyprland.extraLuaFiles = {
    "sounds" = {
      autoLoad = false;
      content = ''
        local sounds = {
          alarmClockElapsed = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/alarm-clock-elapsed.ogg",
          batteryCaution = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/battery-caution.ogg",
          batteryFull = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/battery-full.ogg",
          batteryLow = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/battery-low.ogg",
          bell = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/bell.ogg",
          bellWindowSystem = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/bell-window-system.ogg",
          cameraShutter = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/camera-shutter.wav",
          completeMediaBurn = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/complete-media-burn.ogg",
          completeMediaError = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/complete-media-error.ogg",
          completionFail = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/completion-fail.ogg",
          completionRotation = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/completion-rotation.ogg",
          completionSuccess = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/completion-success.ogg",
          desktopLogin = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-login.ogg",
          desktopLoginLong = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-login-long.ogg",
          desktopLoginShort = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-login-short.ogg",
          desktopLogout = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-logout.ogg",
          deviceAdded = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/device-added.ogg",
          deviceRemoved = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/device-removed.ogg",
          dialogError = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error.ogg",
          dialogErrorCritical = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error-critical.ogg",
          dialogErrorSerious = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error-serious.ogg",
          dialogErrorVerySerious = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error-veryserious.ogg",
          dialogInformation = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-information.ogg",
          dialogQuestion = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-question.ogg",
          dialogSpecial = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-special.ogg",
          dialogWarning = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-warning.ogg",
          fileError = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/file-error.ogg",
          gameOverLoser = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/game-over-loser.ogg",
          gameOverWinner = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/game-over-winner.ogg",
          mediaInsertRequest = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/media-insert-request.ogg",
          messageAttention = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-attention.ogg",
          messageConnectivityProblem = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-conectivity-problem.ogg",
          messageConnectivityError = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-connectivity-error.ogg",
          messageConnectivityErrorSerious = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-connectivity-error-serious.ogg",
          messageConnectivityLost = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-connectivity-lost.ogg",
          messageContactIn = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-contact-in.ogg",
          messageContactOut = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-contact-out.ogg",
          messageError = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-error.ogg",
          messageHighlight = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-highlight.ogg",
          messageIrcEvent = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-irc-event.ogg",
          messageLowpriority = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-lowpriority.ogg",
          messageNewEmail = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-new-email.ogg",
          messageNewInstant = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-new-instant.ogg",
          messageNewSms = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-new-sms.ogg",
          messageSentInstant = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-sent-instant.ogg",
          outcomeFailure = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/outcome-failure.ogg",
          outcomeSuccess = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/outcome-success.ogg",
          phoneIncomingCall = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/phone-incoming-call.ogg",
          powerPlug = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/power-plug.ogg",
          powerUnplug = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/power-unplug.ogg",
          printError = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/print-error.ogg",
          serviceLogin = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/service-login.ogg",
          serviceLogout = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/service-logout.ogg",
          themeDemo = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/theme-demo.ogg",
          trashEmpty = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/trash-empty.ogg",
          windowClose = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-close.ogg",
          windowMaximized = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-maximized.ogg",
          windowMinimized = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-minimized.ogg",
          windowMoveEnd = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-move-end.ogg",
          windowMoveStart = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-move-start.ogg",
          windowPin = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-pin.ogg",
          windowShaded = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-shaded.ogg",
          windowUnpin = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-unpin.ogg",
          windowUnshaded = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-unshaded.ogg"
        }
        return sounds
      '';
    };
  };
}
