{ config, ... }:
{
  wayland.windowManager.hyprland.extraLuaFiles = {
    #load first via underscore
     "_sounds" = {
      autoLoad = true;
      content = ''
        sounds = {
          alarm-clock-elapsed = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/alarm-clock-elapsed.ogg"
          battery-caution = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/battery-caution.ogg"
          battery-full = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/battery-full.ogg"
          battery-low = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/battery-low.ogg"
          bell = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/bell.ogg"
          bell-window-system = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/bell-window-system.ogg"
          camera-shutter = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/camera-shutter.wav"
          complete-media-burn = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/complete-media-burn.ogg"
          complete-media-error = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/complete-media-error.ogg"
          completion-fail = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/completion-fail.ogg"
          completion-rotation = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/completion-rotation.ogg"
          completion-success = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/completion-success.ogg"
          desktop-login = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-login.ogg"
          desktop-login-long = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-login-long.ogg"
          desktop-login-short = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-login-short.ogg"
          desktop-logout = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/desktop-logout.ogg"
          device-added = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/device-added.ogg"
          device-removed = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/device-removed.ogg"
          dialog-error = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error.ogg"
          dialog-error-critical = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error-critical.ogg"
          dialog-error-serious = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error-serious.ogg"
          dialog-error-veryserious = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-error-veryserious.ogg"
          dialog-information = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-information.ogg"
          dialog-question = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-question.ogg"
          dialog-special = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-special.ogg"
          dialog-warning = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/dialog-warning.ogg"
          file-error = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/file-error.ogg"
          game-over-loser = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/game-over-loser.ogg"
          game-over-winner = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/game-over-winner.ogg"
          media-insert-request = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/media-insert-request.ogg"
          message-attention = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-attention.ogg"
          message-conectivity-problem = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-conectivity-problem.ogg"
          message-connectivity-error = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-connectivity-error.ogg"
          message-connectivity-error-serious = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-connectivity-error-serious.ogg"
          message-connectivity-lost = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-connectivity-lost.ogg"
          message-contact-in = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-contact-in.ogg"
          message-contact-out = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-contact-out.ogg"
          message-error = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-error.ogg"
          message-highlight = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-highlight.ogg"
          message-irc-event = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-irc-event.ogg"
          message-lowpriority = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-lowpriority.ogg"
          message-new-email = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-new-email.ogg"
          message-new-instant = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-new-instant.ogg"
          message-new-sms = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-new-sms.ogg"
          message-sent-instant = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/message-sent-instant.ogg"
          outcome-failure = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/outcome-failure.ogg"
          outcome-success = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/outcome-success.ogg"
          phone-incoming-call = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/phone-incoming-call.ogg"
          power-plug = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/power-plug.ogg"
          power-unplug = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/power-unplug.ogg"
          print-error = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/print-error.ogg"
          service-login = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/service-login.ogg"
          service-logout = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/service-logout.ogg"
          theme-demo = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/theme-demo.ogg"
          trash-empty = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/trash-empty.ogg"
          window-close = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-close.ogg"
          window-maximized = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-maximized.ogg"
          window-minimized = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-minimized.ogg"
          window-move-end = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-move-end.ogg"
          window-move-start = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-move-start.ogg"
          window-pin = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-pin.ogg"
          window-shaded = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-shaded.ogg"
          window-unpin = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-unpin.ogg"
          window-unshaded = "${pkgs.kdePackages.oxygen-sounds}/share/sounds/oxygen/stereo/window-unshaded.ogg"
        }
      ''
    };
  };
}
